name: Update beszel

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  update-beszel:
    name: Update beszel
    runs-on: ubuntu-latest
    env:
      MACHINE: beszel
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          hostname: update-beszel-${{ github.run_id }}
          ping: ${{ env.MACHINE }}
          version: latest

      - name: Add SSH key
        env:
          SSH_KEY: ${{ secrets.BESZEL_SSH_KEY }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          MACHINE_IP="$(tailscale ip -4 $MACHINE)"
          ssh-keyscan $MACHINE_IP >> ~/.ssh/known_hosts
          echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/key
          chmod 600 ~/.ssh/key
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add ~/.ssh/key

      - name: Update, upgrade, and cleanup
        run: |
          MACHINE_IP="$(tailscale ip -4 $MACHINE)"
          USERHOST="root@$MACHINE_IP"
          ssh $USERHOST "\
            apt update && \
            apt upgrade -y && \
            apt autoremove -y && \
            apt autoclean && \
            apt clean && \
            journalctl --vacuum-time=7d \
          "
