name: System Update

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  update:
    strategy:
      fail-fast: false
      matrix:
        host:
          - adguard
          - uptime
          - worldstream
          - jalahalli-pi
          - analytics
          - beszel
          - hey-xyz
          - proxmox-1
          - proxmox-2
          - proxmox-3
          - kerala-pi
          - tsflow
          - yoginth-com
    uses: ./.github/workflows/reusable-system-update.yml
    with:
      host: ${{ matrix.host }}
    secrets:
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
