name: Update yoginth-com

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  update-yoginth-com:
    name: Update yoginth-com
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          hostname: update-yoginth-com-${{ github.run_id }}
          version: latest

      - name: Update, upgrade, and cleanup
        run: |
          tailscale ssh root@yoginth-com "\
            apt update && \
            apt upgrade -y && \
            apt autoremove -y && \
            apt autoclean && \
            apt clean && \
            journalctl --vacuum-time=3d \
          "
